---
version: '3.1'
services:
  postgres-server:    # The Postgres Database Service
    image: postgres:latest
    restart: always
    command: postgres -c 'max_connections=300'
    stdin_open: true
    tty: true
    environment:   # Username, password and database name variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata #data storage
    volumes:
      - zabbix_data12:/var/lib/postgresql/data

  zabbix-server:     # The main Zabbix Server Software Service
    image: zabbix/zabbix-server-pgsql:6.2-ubuntu-latest
    restart: always
    environment:   # The Postgres database value variable
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_TIMEOUT: 30
      ZBX_CACHESIZE: '2G'
      ZBX_VALUECACHESIZE: '1G'
      ZBX_STARTDISCOVERERS: 5
      ZBX_STARTPOLLERS: 150
      ZBX_IPMIPOLLERS: 3
      ZBX_STARTHTTPPOLLERS: 10
      ZBX_STARTPOLLERSUNREACHABLE: 5
      ZBX_STARTPINGERS: 10
      ZBX_STARTPREPROCESSORS: 4
    depends_on:
      - postgres-server
    volumes:  # Volumes for scripts and related files you can add
      - /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /usr/bin/bc:/usr/bin/bc
      - /lib/x86_64-linux-gnu/libreadline.so.7:/lib/x86_64-linux-gnu/libreadline.so.7
      - /lib/x86_64-linux-gnu/libtinfo.so.5:/lib/x86_64-linux-gnu/libtinfo.so.5
      - /usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /usr/lib/zabbix/mibs:/var/lib/zabbix/mibs
      - /var/lib/snmp:/var/lib/snmp
      - /var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - /usr/bin:/host/bin
    ports:
      - 10051:10051

  zabbix-web:    # The main Zabbix web UI or interface
    image: zabbix/zabbix-web-nginx-pgsql:6.2-ubuntu-latest
    restart: always
    environment:  # Postgre database variables
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server  # Zabbix related and Php variables
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Africa/Banjul"
      ZBX_MAXEXECUTIONTIME: 500
    depends_on:
      - postgres-server
      - zabbix-server
    ports:    # Port where Zabbix UI is available
      - 8090:8080

  zabbix-agent:   # Zabbix agent service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent:6.2-ubuntu-latest
    privileged: true   #access mode for allowing resource access
    restart: unless-stopped
    environment:
      - ZBX_PASSIVESERVERS=zabbix-server
    #  - ZBX_LOADMODULE=zabbix_module_docker.so
    ports:    # Port where Zabbix UI is available
      - 10050:10050
    volumes:  # Volumes for scripts and related files you can add
      - /var/lib/zabbix-agent-modules:/var/lib/zabbix/modules/
      - /var/run/docker.sock:/var/run/docker.sock

  zabbix-snmptraps: #Receiving SNMP traps to Zabbix server or Zabbix proxy 
    image: zabbix/zabbix-snmptraps:6.2-ubuntu-latest
    privileged: true   #access mode for allowing resource access
    restart: unless-stopped
    depends_on:
      - zabbix-server
    ports:
      - "162:1162/udp" #port number for snmp
    volumes: #The volume contains log file snmptraps.log named with received SNMP traps.
      - snmptraps:/var/lib/zabbix/snmptraps:rw
      - snmpmibs:/var/lib/zabbix/mibs:rw


  adminer:  #Optional for accessing databases
    image: adminer
    restart: always
    ports:
      - 8080:8080
  grafana-xxl:  #optional more functional and creative UI
  #image: monitoringartist/grafana-xxl:latest
    image: grafana/grafana-oss
    container_name: grafana
    user: "0:0" # give root permission 
    restart: unless-stopped
    depends_on:
      - zabbix-web
      - zabbix-agent
      - zabbix-server
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
     - 3000:3000
    volumes:
     - /var/lib/grafana:/var/lib/grafana
volumes:
  zabbix_data12:
  snmptraps:
  snmpmibs:

