---
version: '3.1'
services:
  zabbix-agent:   # Zabbix agent2 service that tracks usage and send to zabbix server
    image: zabbix/zabbix-agent2:6.2-ubuntu-latest
    privileged: true   #access mode for allowing resource access
    restart: unless-stopped
    environment:
      - ZBX_PASSIVESERVERS=zabbix-server
      - ZBX_ACTIVESERVERS=zabbix-server:10051 #active mode server parameters 
    #  - ZBX_LOADMODULE=zabbix_module_docker.so
    ports:    # Port where Zabbix UI is available
      - 10050:10050
    volumes:  # Volumes for scripts and related files you can add
      - /var/lib/zabbix-agent-modules:/var/lib/zabbix/modules/
      - /var/run/docker.sock:/var/run/docker.sock